package Email;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 59268
 */

import java.util.*;  
import javax.mail.*;  
import javax.mail.internet.*;  
 

public class SendEmail {
    
    
    public SendEmail(){};
    
    public String send(){
        String out="";
        String to = "nandlallnarain2020@gmail.com";

      // Put sender’s address
      String from = "peoplepay@gplinc.com";
      final String username = "peoplepay@gplinc.com";//username generated by Mailtrap
      final String password = "14i@AMbb";//password generated by Mailtrap

      // Paste host address from the SMTP settings tab in your Mailtrap Inbox
      String host = "webmail.gplinc.com";

      Properties props = new Properties();
      props.put("mail.smtp.auth", "true");
      props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap  
      props.put("mail.smtp.host", host);
      props.put("mail.smtp.port", "465");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

      // Get the Session object.
      Session session = Session.getInstance(props,
         new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
               return new PasswordAuthentication(username, password);
    }
         });
      
      
      try {
    // Create a default MimeMessage object.
    Message message = new MimeMessage(session);
 
    // Set From: header field 
    message.setFrom(new InternetAddress(from));
 
    // Set To: header field
    message.setRecipients(Message.RecipientType.TO,
               InternetAddress.parse(to));
 
    // Set Subject: header field
    message.setSubject("My first message with JavaMail");
 
    // Put the content of your message
    message.setText("Hi there, this is my first message sent with JavaMail");

    // Send message
    Transport.send(message);

    System.out.println("Sent message successfully....");
    out="ok";
      } catch (MessagingException e) {
         out=e.getMessage();
         throw new RuntimeException(e);
      }
      
     return out;
    
    }
    
    
    
    public String sendGmail(){
        String out="";
        
    String remitente = "angel.amet";  //Para la dirección nomcuenta@gmail.com

    Properties props = System.getProperties();
    props.put("mail.smtp.host", "smtp.gmail.com");  //El servidor SMTP de Google
    props.put("mail.smtp.user", remitente);
    props.put("mail.smtp.clave", "Oniulys.2019.Guyana");    //La clave de la cuenta
    props.put("mail.smtp.auth", "true");    //Usar autenticación mediante usuario y clave
    props.put("mail.smtp.starttls.enable", "true"); //Para conectar de manera segura al servidor SMTP
    props.put("mail.smtp.port", "587"); //El puerto SMTP seguro de Google

    Session session = Session.getDefaultInstance(props);
    MimeMessage message = new MimeMessage(session);

    try {
        message.setFrom(new InternetAddress(remitente));
        InternetAddress[] addresses = InternetAddress.parse("aherrera@innosysgy.com");//one or more addresses
        message.addRecipient(Message.RecipientType.TO, addresses[0]);   //Se podrían añadir varios de la misma manera
        
        message.setSubject("testeando");
        message.setText("cuerpo");
        Transport transport = session.getTransport("smtp");
        transport.connect("smtp.gmail.com", remitente, "Oniulys.2019.Guyana");
        transport.sendMessage(message, message.getAllRecipients());
        transport.close();
        out="ok";
    }
    catch (MessagingException me) {
        out=me.getMessage();
        me.printStackTrace();   //Si se produce un error
    }
        
      
        return out;
    
    }
    
    
    
 
    
    public String sendPasswrodReset(String emailAddress, String reset_code){
        String out="";
        String to = emailAddress;

      // Put sender’s address
      String from = "apps@innosysgy.com";
      final String username = "a9665f9d497d359661be18440ecaf564";//username generated by Mailtrap
      final String password = "1e2e311da8066cb31f6e1f79575a86e4";//password generated by Mailtrap

      // Paste host address from the SMTP settings tab in your Mailtrap Inbox
      String host = "in-v3.mailjet.com";

      Properties props = new Properties();
      props.put("mail.smtp.auth", "true");
      props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap  
      props.put("mail.smtp.host", host);
      props.put("mail.smtp.port", "25");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

      // Get the Session object.
      Session session = Session.getInstance(props,
         new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
               return new PasswordAuthentication(username, password);
    }
         });
      
      
      try {
    // Create a default MimeMessage object.
    Message message = new MimeMessage(session);
    
  
 
    // Set From: header field 
    message.setFrom(new InternetAddress(from));
 
    // Set To: header field
    message.setRecipients(Message.RecipientType.TO,
               InternetAddress.parse(to));
 
    // Set Subject: header field
    message.setSubject("FarmersMarket.GY - Password Reset");
    String url="https://bfe1jra07zihlbs-innosysdb2019.adb.us-ashburn-1.oraclecloudapps.com/ords/f?p=116:2:::::P2_CODE:"+reset_code;
    // Put the content of your message
    String mess="A password reset request has been received.<br />\n" +
"                        Your Username is "+emailAddress+"<br /><br />\n" +
"                        Click the link below to reset your password.<br /><br />\n" +
"                        Your password will be set to <b>\"password\"</b> (without quotes) after you click the link.<br /><br />\n" +
"\n" +
"                        After you click the link use:<br /><br />\n" +
"\n" +
"                        Username: "+emailAddress+"<br />\n" +
"                        Password: password<br /><br />\n" +
"                        <a href="+url+">Reset Account</a>";
    //message.setText(mess);
    
    message.setContent(mess,"text/html;charset=iso-8859-1");
    

    // Send message
    Transport.send(message);

    System.out.println("Sent message successfully....");
    out="ok";
      } catch (MessagingException e) {
         out=e.getMessage();
         throw new RuntimeException(e);
      }
      
     return out;
    
    }
    
    
    
   
   
    
}
   
    
